workflows:
  ios-native-workflow:
    name: iOS Native (TestFlight)
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic # Убедитесь, что интеграция с именем "codemagic" настроена в Codemagic
    environment:
      ios_signing:
        distribution_type: app_store # Тип распространения для TestFlight
        bundle_identifier: io.codemagic.sample.iosnative # Идентификатор приложения
      vars:
        BUNDLE_ID: "io.codemagic.sample.iosnative" # Должен совпадать с идентификатором в Xcode и App Store Connect
        XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # Имя вашего рабочего пространства Xcode
        XCODE_SCHEME: "CodemagicSample" # Имя схемы в Xcode
        APP_STORE_APPLE_ID: 1555555551 # Apple ID приложения из App Store Connect
      xcode: latest # Используем последнюю версию Xcode
      cocoapods: default # Используем стандартную версию CocoaPods
    scripts:
      - name: Установка зависимостей CocoaPods
        script: |
          pod install
      - name: Настройка профилей подписи в проекте Xcode
        script: |
          xcode-project use-profiles --verbose # Включаем подробное логирование для диагностики
      - name: Увеличение номера сборки
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Сборка IPA для распространения
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --verbose # Включаем подробное логирование
    artifacts:
      - build/ios/ipa/*.ipa # Собранный IPA-файл
      - /tmp/xcodebuild_logs/*.log # Логи Xcode для диагностики
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true # Уведомлять при успешной сборке
          failure: false # Не уведомлять при сбое
      app_store_connect:
        auth: integration # Используем интеграцию App Store Connect
        submit_to_testflight: true # Отправка сборки в TestFlight
        beta_groups: # Группы тестировщиков в TestFlight
          - group name 1
          - group name 2
        submit_to_app_store: false # Отключена отправка в App Store